<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_residents',
		'title' => 'Residents',
		'fields' => array (
			array (
				'key' => 'field_5705f16a1bd20',
				'label' => 'Resident type',
				'name' => 'resident_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5702b1ac2ae46',
				'label' => 'Start year',
				'name' => 'start_year',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					2000 => 2000,
					2001 => 2001,
					2002 => 2002,
					2003 => 2003,
					2004 => 2004,
					2005 => 2005,
					2006 => 2006,
					2007 => 2007,
					2008 => 2008,
					2009 => 2009,
					2010 => 2010,
					2011 => 2011,
					2012 => 2012,
					2013 => 2013,
					2014 => 2014,
					2015 => 2015,
					2016 => 2016,
					2017 => 2017,
					2018 => 2018,
					2019 => 2019,
					2020 => 2020,
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5702b1d52ae47',
				'label' => 'End year',
				'name' => 'end_year',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					2000 => 2000,
					2001 => 2001,
					2002 => 2002,
					2003 => 2003,
					2004 => 2004,
					2005 => 2005,
					2006 => 2006,
					2007 => 2007,
					2008 => 2008,
					2009 => 2009,
					2010 => 2010,
					2011 => 2011,
					2012 => 2012,
					2013 => 2013,
					2014 => 2014,
					2015 => 2015,
					2016 => 2016,
					2017 => 2017,
					2018 => 2018,
					2019 => 2019,
					2020 => 2020,
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5696bd3588249',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5aa437f01f96b',
				'label' => 'Email address',
				'name' => 'email',
				'type' => 'text',
				'instructions' => 'not shown publicly',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5aa43f17ed630',
				'label' => 'Links',
				'name' => 'links',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5aa43f23ed631',
						'label' => 'Link title',
						'name' => 'link_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5aa43f2eed632',
						'label' => 'Link URL',
						'name' => 'link_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_5aa4383c6d960',
				'label' => 'Collaboration member',
				'name' => 'collaboration_member',
				'type' => 'radio',
				'choices' => array (
					'show' => 'Had individual residency (show)',
					'hide' => 'Only residency was collaboration (hide)',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'show',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_5aa437aa1f969',
				'label' => 'Members',
				'name' => 'members',
				'type' => 'relationship',
				'instructions' => 'each member in a collaboration',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'resident',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_5aa1b7e8b1f99',
				'label' => 'Show Related Readings',
				'name' => 'show_related_readings',
				'type' => 'radio',
				'choices' => array (
					'show' => 'Show Related Readings',
					'hide' => 'Hide Related Readings',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'show',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resident',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
