<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_residents',
		'title' => 'Residents',
		'fields' => array (
			array (
				'key' => 'field_5705f16a1bd20',
				'label' => 'Resident type',
				'name' => 'resident_type',
				'type' => 'select',
				'required' => 1,
				'choices' => array(
					'resident' => 'Resident',
					'rapid-response-fellow' => 'Rapid Response Fellow',
				),
				'default_value' => 'resident',
			),
			array (
				'key' => 'field_5702b1ac2ae46',
				'label' => 'Start year',
				'name' => 'start_year',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					2000 => 2000,
					2001 => 2001,
					2002 => 2002,
					2003 => 2003,
					2004 => 2004,
					2005 => 2005,
					2006 => 2006,
					2007 => 2007,
					2008 => 2008,
					2009 => 2009,
					2010 => 2010,
					2011 => 2011,
					2012 => 2012,
					2013 => 2013,
					2014 => 2014,
					2015 => 2015,
					2016 => 2016,
					2017 => 2017,
					2018 => 2018,
					2019 => 2019,
					2020 => 2020,
					2021 => 2021,
					2022 => 2022,
					2023 => 2023,
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5702b1d52ae47',
				'label' => 'End year',
				'name' => 'end_year',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					2000 => 2000,
					2001 => 2001,
					2002 => 2002,
					2003 => 2003,
					2004 => 2004,
					2005 => 2005,
					2006 => 2006,
					2007 => 2007,
					2008 => 2008,
					2009 => 2009,
					2010 => 2010,
					2011 => 2011,
					2012 => 2012,
					2013 => 2013,
					2014 => 2014,
					2015 => 2015,
					2016 => 2016,
					2017 => 2017,
					2018 => 2018,
					2019 => 2019,
					2020 => 2020,
					2021 => 2021,
					2022 => 2022,
					2023 => 2023,
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5696bd3588249',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5aa437f01f96b',
				'label' => 'Email address',
				'name' => 'email',
				'type' => 'text',
				'instructions' => 'not shown publicly',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5aa43f17ed687',
				'label' => 'Resident Bio',
				'name' => 'resident_bio',
				'type' => 'wysiwyg',
				'column_width' => '',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5aa43f17ed68799',
				'label' => 'Resident Pullquote',
				'name' => 'resident_pullquote',
				'type' => 'wysiwyg',
				'column_width' => '',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5aa437f01f96b9999',
				'label' => 'Featured Video',
				'name' => 'featured_video',
				'type' => 'text',
				'instructions' => 'Displays above content',
				'placeholder' => 'Paste a Youtube Video URL',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5aa4383c6d939',
				'label' => 'Link to Artist Website',
				'name' => 'link_target',
				'type' => 'radio',
				'choices' => array (
					'internal' => 'Resident Page (on Eyebeam)',
					'external' => 'External Artist Website',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'external',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_5aa43f17ed630',
				'label' => 'Links',
				'name' => 'links',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5aa43f23ed631',
						'label' => 'Link title',
						'name' => 'link_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5aa43f2eed632',
						'label' => 'Link URL',
						'name' => 'link_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_5aa4383c6d960',
				'label' => 'Collaboration member',
				'name' => 'collaboration_member',
				'type' => 'radio',
				'choices' => array (
					'show' => 'Had individual residency (show)',
					'hide' => 'Only residency was collaboration (hide)',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'show',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_5aa437aa1f969',
				'label' => 'Members',
				'name' => 'members',
				'type' => 'relationship',
				'instructions' => 'each member in a collaboration',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'resident',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_5aa1b7e8b1f89',
				'label' => 'Show Related Readings Automatically',
				'name' => 'show_related',
				'type' => 'radio',
				'choices' => array (
					'auto' => 'Show Related Readings Automatically',
					'manual' => 'Manually Select Related Readings',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'manual',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_586bce21ov23',
				'label' => 'Related Readings',
				'name' => 'related_readings',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'event,post,project,archive',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5aa1b7e8b1f89',
							'operator' => '==',
							'value' => 'manual',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_j2k8xs',
				'label' => 'Media',
				'name' => 'media',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_ysp1s',
						'label' => 'Media type',
						'name' => 'media_type',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'image' => 'Image',
							'video_url' => 'Video URL',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_yc3l7a',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_ysp1s',
									'operator' => '==',
									'value' => 'image',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_h1jcyy',
						'label' => 'Video URL',
						'name' => 'video_url',
						'type' => 'text',
						'instructions' => 'currently only YouTube URLs work',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_ysp1s',
									'operator' => '==',
									'value' => 'video_url',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_556aba43rg',
						'label' => 'Caption',
						'name' => 'caption',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Media',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resident',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
